type: http
name: Get identity and application provisioning status
url: '{{baseUrl}}/workers/:workerId/provisioning-status'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: workerId
    value: d321209e-2d75-6f2e-d044-4bbe0d65ac89
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "workerId": "971ea19d-dddb-bc07-4c63-54713b4bacc8",
            "identityStatus": "not_started",
            "laptopStatus": "failed",
            "applicationAccess": [
              {
                "systemName": "string",
                "status": "completed"
              },
              {
                "systemName": "string",
                "status": "in_progress"
              }
            ]
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Provisioning state
