type: http
name: Get identity and application provisioning status
url: '{{baseUrl}}/workers/:workerId/provisioning-status'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: workerId
    value: 1bc2a279-4c05-b693-4010-a73636fcae64
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "workerId": "d321acf2-cb28-ebfd-5c93-2d4a322e6104",
            "identityStatus": "in_progress",
            "laptopStatus": "not_started",
            "applicationAccess": [
              {
                "systemName": "string",
                "status": "failed"
              },
              {
                "systemName": "string",
                "status": "completed"
              }
            ]
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Provisioning state
